[package]
name = "bc-scraper2"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.5.2"
ggez = "0.5.1"
rand = "0.7.3"
rand_distr = "0.2.2"
rayon = "1.3.0"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "native-tls", "gzip", "brotli"] }
url = { version = "2.3.1", default-features = false }
chrono = { version = "0.4.22", default-features = false }
rusqlite = { version = "0.28.0", default-features = false, features = ["chrono", "url", "bundled"] }
fehler = { version = "1.0.0", default-features = false }
anyhow = { version = "1.0.65", default-features = false, features = ["std"] }
tracing = { version = "0.1.36", default-features = false }
tracing-subscriber = { version = "0.3.15", default-features = false, features = ["std", "env-filter", "fmt"] }
