[package]
name = "sim"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hecs = { version = "0.5.2", default-features = false }
rayon = { version = "1.3.0", default-features = false }

data = { version = "0.0.0", path = "../data" }
phys = { version = "0.0.0", path = "../phys" }
